---
- hosts: webservers
  become: yes
 
  tasks:
  - name: ensure that apache is installed
    yum: name=httpd state=present
    when: ansible_os_family == "RedHat"

  - name: start the apache service
    service: name=httpd state=started

- hosts: dbservers
  become: yes

  tasks:
  - name: ensure mysql is installed
    yum: name=mysql-server state=present
    when: ansible_os_family == "RedHat"
  - name: start mysql
    service: name=mysqld state=started

- hosts: dbservers:webservers
  become: yes

  tasks: 
  - name: stop iptables now
    service: name=iptables state=stopped
